services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: my-db
    volumes:
    - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  frontend:
    depends_on:
      - mongo
    build: ./map-site
    restart: unless-stopped
    container_name: map-site
    ports:
    - "3000:3000"

  backend:
    depends_on:
        - mongo
    build: ./telegram
    restart: unless-stopped
    container_name: python-app

  summarizer:
    build: ./summarizer
    restart: unless-stopped
    container_name: summarizer
