location_list  = ['Alchevsk',
                'Alushta',
                'Antratsyt',
                'Bakhmut',
                'Berdyansk',
                'Bila',
                'Tserkva',
                'Bilhorod-Dnistrovskyi',
                'Bolhrad',
                'Boryspil',
                'Brody',
                'Brovary',
                'Bryanka',
                'Cherkasy',
                'Chernihiv',
                'Chernivtsi',
                'Chervonohrad',
                'Dnipro',
                'Donetsk',
                'Drohobych',
                'Enakievo',
                'Energodar',
                'Evpatoria',
                'Fastiv',
                'Feodosia',
                'Glukhov',
                'Gorlovka',
                'Ivano-Frankivsk',
                'Izmail',
                'Izyum',
                'Kalush',
                'Kamenets',
                'Podolskiy',
                'Kamianske',
                'Kerch',
                'Kharkiv',
                'Khartsyzsk',
                'Kherson',
                'Khmelnitsky',
                'Kiev',
                'Kolomiya',
                'Konotop',
                'Konstantinovka',
                'Korosten',
                'Kovel',
                'Kramatorsk',
                'Krasnodon',
                'Kremenchug',
                'Kremenets',
                'Krivoy',
                'Rog',
                'Kropyvnytskyi',
                'Lisichansk',
                'Lubny',
                'Lugansk',
                'Lutsk',
                'Lviv',
                'Makeevka',
                'Mariupol',
                'Melitopol',
                'Mirgorod',
                'Mukachevo',
                'Nikolaev',
                'Nikopol',
                'Nizhyn',
                'Odessa',
                'Okhtyrka',
                'Oleksandriya',
                'Pavlograd',
                'Pochaev',
                'Poltava',
                'Priluki',
                'Pripyat',
                'Rivne',
                'Romny',
                'Sevastopol',
                'Severodonetsk',
                'Shostka',
                'Simferopol',
                'Slavyansk',
                'Smila',
                'Stakhanov',
                'Stryi',
                'Sudak',
                'Sumy',
                'Svetlovodsk',
                'Ternopil',
                'Truskavets',
                'Uman',
                'Uzhgorod',
                'Vinnitsa',
                'Yalta',
                'Yuzhnoukrainsk',
                'Zaporozhye',
                'Zhitomir',
                'Zhovti',
                'Vody']

coord_dict = {'Kyiv': 	    [50.45466, 30.5238],
            'Kharkiv': 	    [49.98081, 36.25272],
            'Donetsk': 	    [48.023, 37.80224],
            'Odessa': 	    [46.48572, 30.74383],
            'Dnipro': 	    [48.46664, 35.04066],
            'Lviv': 	    [49.83826, 24.02324],
            'Mariupol':     [47.09514, 37.54131],
            'Luhansk': 	    [48.56705, 39.31706],
            'Sevastopol': 	[44.60795, 33.52134],
            'Zaporizhzhya': [47.85167, 35.11714],
            'Simferopol':   [44.95719, 34.11079],
            'Kryvyy Rih':   [47.90572, 33.39404],
            'Chernihiv':    [51.50551, 31.28487],
            'Sumy':         [50.9216, 34.80029],
            'Kherson': 	    [46.63695, 32.61458],
            'Poltava': 	    [49.58925, 34.55367],
            'Zhytomyr': 	[50.26487, 28.67669],
            'Horlivka': 	[48.33576, 38.05325],
            'Cherkasy': 	[49.44452, 32.05738],
            'Chernivtsi': 	[48.29045, 25.93241],}